### ISSUE TITLE
import clep.sample_scoring   

### ISSUE THREAD

**Issue by wgfwang** [hybrid-kg/clep#23]
![mmexport1631785472563](https://user-images.githubusercontent.com/80140818/133590104-a9772c36-3881-4870-8ea7-0ed18fcf9751.png)
run    'import clep.sample_scoring'
 The error as shown in the figure above appears, how to solve it

**Comment by vinaysb** [comment]
Do you have R language installed?

**Comment by wgfwang** [comment]
> Do you have R language install

> Do you have R language installed?

I have installed R and tried several versions of it, but this is the error. Is it the version? Which version of R do you use

**Comment by vinaysb** [comment]
This seems to be an issue with R on Windows. I would recommend following this [link](https://stackoverflow.com/a/63865448) and editing your PATH variable. 

Also as for the R version, I would recommend using 4.0+. The exact version that I use is 4.0.3.

**Comment by wgfwang** [comment]
Thank you very much for your answer! Problem solved. 
But I still have a question. Could you please understand the **design file** in detail? I only have gene expression data, no design file, I want to generate a new embed through CLEP.
