### ISSUE TITLE
   gf

### ISSUE THREAD

**Issue by wgfwang** [hybrid-kg/clep#24]
![IMG_20210917_153521](https://user-images.githubusercontent.com/80140818/133743404-e9d8d7d6-d26a-42bb-9c20-b36f0c5cba0a.png)
clep.sample_scoring.radical_search.do_radical_search(design＝？)     
Can you explain in detail what Target is in the design file? I don't really understand this. Looking forward to your reply! thank you！

**Comment by vinaysb** [comment]
It's a column that represents the group that a sample belongs to. For example, Sample_3 is the control while Sample_1 and Sample_2 are samples from patients who have the disease. There can be more than 2 groups, but 2 is minimum, and one of them has to be the control group.

**Comment by wgfwang** [comment]
![image](https://user-images.githubusercontent.com/80140818/135736755-e8cd99bb-329a-47d4-a0e3-b20d5b59b728.png)

Above is the exact words of your published article <clep>.
I have one last last question,can you explain the steps of eCDF to select the most informative features? I read your paper and I didn't understand this part. I look forward to and thank you for your reply!

**Comment by wgfwang** [comment]
> It's a column that represents the group that a sample belongs to. For example, Sample_3 is the control while Sample_1 and Sample_2 are samples from patients who have the disease. There can be more than 2 groups, but 2 is minimum, and one of them has to be the control group.

![image](https://user-images.githubusercontent.com/80140818/135737340-4fcc1490-8b50-48e7-8e42-1be7545428d5.png)
Above is the exact words of your published article《CLEP》 .
I have one last last question,can you explain the steps of eCDF to select the most informative features? I read your paper and I didn't understand this part. I look forward to and thank you for your reply!
