### ISSUE TITLE
How to use GPU for training

### ISSUE THREAD

**Issue by wgfwang** [hybrid-kg/clep#25]
![edecff871d92a0102ae701060cb4cd9](https://user-images.githubusercontent.com/80140818/134449855-fbd676a1-3eba-4884-a69f-3e0d9d0395dd.png)

**Comment by wgfwang** [comment]
> Have you installed CUDA on your system?

But CUDA is for TensorFlow. Can you explain in detail how to use CUDA for CLEP? Thank you very much!

**Comment by wgfwang** [comment]
> Have you installed CUDA on your system?

Yes,but CUDA is for TensorFlow. Can you explain in detail how to use CUDA for CLEP? Thank you very much!

**Comment by vinaysb** [comment]
CLEP uses PyKEEN, which is built using PyTorch. PyKEEN provides the neural network necessary for patient embedding. 

This is not necessarily an error. PyKEEN can also run on the CPU and does not need the GPU and CUDA.

**Comment by wgfwang** [comment]
Ok, using CPU is just too slow. I have another question, can you explain the steps of eCDF to select the most informative features? I read your paper and I didn't understand this part. I look forward to and thank you for your reply!

**Comment by wgfwang** [comment]
> CLEP uses PyKEEN, which is built using PyTorch. PyKEEN provides the neural network necessary for patient embedding.
> 
> This is not necessarily an error. PyKEEN can also run on the CPU and does not need the GPU and CUDA.

Ok, using CPU is just too slow.
 I have another question, can you explain the steps of eCDF to select the most informative features? I read your paper and I didn't understand this part. I look forward to and thank you for your reply!
