### ISSUE TITLE
sample data files

### ISSUE THREAD

**Issue by ghost** [hybrid-kg/clep#27]
Hi

Would it be possible to provide sample data, design files, etc to test if the installation is correct? if we can replicate some of the plots in the paper that would be great!

Thank you!

**Comment by vinaysb** [comment]
The scripts in the example directory should be able to provide you with examples for the data files. 

But you will not be able to replicate the plots as we are using the ADNI dataset which is not open access. You can download the ADNI dataset and run the framework on the data files to replicate the results
