### ISSUE TITLE
pip install clep cant not install 

### ISSUE THREAD

**Issue by vkmk47** [hybrid-kg/clep#29]
I tried to run the command line "pip install clep" but I get the following error (please see my Screenshot). 
How do I reopen it please? 
I have python version 3.8.10 

![Screenshot 2021-11-19 114138](https://user-images.githubusercontent.com/49484009/142609730-1015feed-274d-4032-af8b-373b3d22be17.png)

**Comment by Shraddha-Mane** [comment]
I am getting same error when I install using pip. Any solution?

**Comment by vinaysb** [comment]
It seems that pip is not able to find your R installation. Can you make sure you have R installed and it's accessible to your python environment? If you have R installed, try to explicitly set the "R_HOME" env variable to point to the R directory, and also add the R bin directory to your PATH variable

**Comment by vkmk47** [comment]
@Shraddha-Mane  yes! 
I downloaded the file "configclep.yml" which I put in the C drive of my computer and using this file I created an environment with all the dependencies including the "clep" library by executing the following command: 'conda env create -f conficlep.yml'. 

Because I use python on Anaconda, I executed this command in Anaconda-promt.  

i provide you with the file 'configclep.yml' that you can simply download, open and create an empty yml file. copy all the content of your .txt file and add it to your new .yml file previously created and save it in the c drive of your computer.   

![PHOTO-2021-11-21-01-38-54](https://user-images.githubusercontent.com/49484009/145225280-9ffb66b6-41d3-48ce-9e76-3da2ae4687ef.jpg)

![PHOTO-2021-11-21-01-25-17](https://user-images.githubusercontent.com/49484009/145225452-b3f84eb3-9dfb-4260-a6c5-14f06dc539b2.jpg)

**Comment by vkmk47** [comment]
Please @vinaysb, 
how do I explicitly set the "R_HOME" environment variable to point to the R directory, if I use Anaconda Promt to run the command lines? 


jai deja generé les parametres suivants <DATA_FILE> --d <DESIGN_FILE> et souhaite á present executer dans Anaconda Promt la commande suisvante qui ne fonctione pas: 

$ clep sample-scoring radical-search --data <DATA_FILE> --design <DESIGN_FILE> --control Control --threshold 2.5 --control_based --ret_summary --out <OUTPUT_DIR>

je suppose l'erreur est toujours liée faut fait mon environnement n'a pas d'acces á R .

**Comment by vinaysb** [comment]
@vkmk47 Yes this error basically is because python is not able to detect the location of the R binary file. On anaconda, you can check if anaconda's bin directory is part of the PATH variable, and add it if not. 

If that does not work then I would recommend checking the [rpy2 repo](https://github.com/rpy2/rpy2) for further assistance.

**Comment by smaritem** [comment]
Hi everyone,

add in your systemvariable the key < R_HOME >  and the value < C:\Program Files\R\R-4.x.x >    AND also
add in PATH the value < C:\Program Files\R\R-4.x.x\bin\x64 >

Thanks

**Comment by vkmk47** [comment]
Hi @smaritem , 
Thanks to you. 
your solution helped me to move forward. 
After successfully executing the command line 'Radical Search' in the following picture: 
![Radical Search](https://user-images.githubusercontent.com/49484009/145687328-23dda142-d72a-4ac6-9270-f107f1334b8e.PNG)

but when I execute command line 2 ('Graph generation') of the same photo, I get the following error:
![Error](https://user-images.githubusercontent.com/49484009/145687479-146860c8-2b45-4a4e-a3a8-9a385836a719.PNG)

thanks for your help

**Comment by vkmk47** [comment]
@vinaysb @smaritem @Shraddha-Mane @cthoyt 
Hi everyone,

could you please help me solve or to fixe my current problem? 

I got the error (on my console picture) when I executed the following line of code:

clep embedding generate-network --data <SCORED_DATA_FILE> --method interaction_network --ret_summary --out <OUTPUT_DIR>

![Error](https://user-images.githubusercontent.com/49484009/145687479-146860c8-2b45-4a4e-a3a8-9a385836a719.PNG)
